### ISSUE TITLE
Problems on Windows Server 2012 R2

### ISSUE THREAD

**Issue by gonace** [JulioQc/WinDHCP#1]
Hi
First I'd like to inform that I'm no NXLog expert, so I'm trying to use this content_pack for my Graylog instance. 

When restarting NXLog it says:
`2016-08-07 16:10:09 ERROR failed to open directory: C:\Windows\System32\dhcp: The system cannot find the path specified.  
2016-08-07 16:10:09 WARNING Module in_dhcp has no input files to read`

But the path "C:\Windows\System32\dhcp" is accessible and contains a bunch of files including the log giles for the DHCP Server.

DhcpSrvLog-Mon/Tue/Wed/Thu/Fri/Sat/Sun 

Any idea of why?

My configuration
`<Input in_dhcp>
    Module im_file
    File "C:\Windows\System32\dhcp\DhcpSrvLog-*.log"
    PollInterval 1
    SavePos True
    ReadFromLast True
    Recursive False
    RenameCheck True
    Exec $FileName = file_name(); # Send file name with each message
</Input>`

`<Output out_dhcp>
    Module om_udp
    Host 10.0.0.14
    Port 5442
    OutputType  GELF
    Exec $short_message = $raw_event; # Avoids truncation of the short_message field.
    Exec $gl2_source_collector = 'ae1187a3-48ae-42bc-a820-7033d7438dbd';
    Exec $Hostname = hostname_fqdn();
</Output>`

**Comment by gonace** [comment]
Sorry my bad, using "Sysnative" worked...

**Comment by JulioQc** [comment]
No problem, it took me a while too to figure out to use the "Sysnative" patch instead ;)
Glad it worked!
